<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Using Include="System.IO" />
    <InternalsVisibleTo Include="Ream.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ream.Core\Ream.Core.csproj" />
    <ProjectReference Include="..\Ream.Persistence\Ream.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
